In [18]:
import numpy as np

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [3]:
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]

C = np.dot(A, B)
C

array([[19, 22],
       [43, 50]])

In [19]:
print(arr2d[0, 1])  # Row 0, Column 1 → 2


2


In [20]:
print(arr2d[1, :])  # Row 1 → [4 5 6]


[4 5 6]


In [21]:
print(arr2d[:, 2])  # Column 2 → [3 6 9]


[3 6 9]


In [22]:
print(arr2d[0:2, 1:3])  # Rows 0-1, Columns 1-2


[[2 3]
 [5 6]]


In [23]:
print(arr2d + 10)    # Add 10 to every element
print(arr2d * 2)     # Multiply every element by 2
print(arr2d.T)       # Transpose → rows ↔ columns


[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [24]:
arr3d = np.array([[[1, 2, 3],   # Layer 0
                   [4, 5, 6]],

                  [[7, 8, 9],   # Layer 1
                   [10, 11, 12]]])
print(arr3d)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
print(arr3d[1, 0, 2])  # Layer 1, Row 0, Column 2 → 9
print(arr3d[0])  # Layer 0
print(arr3d[:, 1, :])  # Row 1 of all layers


9
[[1 2 3]
 [4 5 6]]
[[ 4  5  6]
 [10 11 12]]


In [26]:
print(arr3d[:, :, 1:3])  # All layers, all rows, columns 1-2
print(arr3d + 5)  # Add 5 to every element
print(arr3d * 2)  # Multiply every element by 2


[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]
[[[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]


In [27]:
import numpy as np

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

print("Original:\n", arr2d)
print("Transpose:\n", arr2d.T)


Original:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [28]:
arr3d_flat = arr3d.reshape(3, 2, 2)  # New shape
print(arr3d_flat.shape)


(3, 2, 2)


In [38]:
arr3d = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]]])

# Swap axes: (layers, rows, cols) → (l3ayers, cols, rows)
transposed = np.transpose(arr3d, (0, 2, 1))
print(transposed)


[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


In [39]:
print(arr2d[::-1, :])
print(arr2d[:, ::-1])
print(arr2d[::-1, ::-1])


[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]
[[6 5 4]
 [3 2 1]]


In [40]:
print(arr3d[::-1, :, :])
print(arr3d[:, ::-1, :])
print(arr3d[:, :, ::-1])


[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]
[[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]]
[[[ 3  2  1]
  [ 6  5  4]]

 [[ 9  8  7]
  [12 11 10]]]


In [41]:
# Flip array upside down (vertical)
print(np.flip(arr2d, axis=0))

# Flip left-right (horizontal)
print(np.flip(arr2d, axis=1))

# Flip both
print(np.flip(arr2d))


[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]
[[6 5 4]
 [3 2 1]]


In [42]:
print(np.flip(arr3d, axis=1))  # Flip rows in all layers


[[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]]


In [43]:
# 2D array rotation
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(np.rot90(arr))  # Rotate 90° counter-clockwise
print(np.rot90(arr, k=2))  # Rotate 180°


[[3 6 9]
 [2 5 8]
 [1 4 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
