In [1]:
import numpy as np

In [2]:
zeros = np.zeros((3, 3))  # 3x3 array of zeros
ones = np.ones((2, 4))    # 2x4 array of ones
identity = np.eye(4)       # 4x4 identity matrix
print(zeros)
print(ones)
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
zeros = np.zeros((3, 3), dtype=np.uint8)  # 3x3 array of zeros
ones = np.ones((2, 4), dtype=np.uint8)    # 2x4 array of ones
identity = np.eye(4, dtype=np.uint8)       # 4x4 identity matrix
print(zeros)
print(ones)
print(identity)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1 1]
 [1 1 1 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   # Dimensions (rows, columns) → (2, 3)
print(arr.ndim)    # Number of dimensions → 2
print(arr.size)    # Total elements → 6
print(arr.dtype)   # Data type → int64


(2, 3)
2
6
int64


In [5]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])      # First element → 10
print(arr[-1])     # Last element → 50
print(arr[1:4])    # Slice → [20 30 40]
print(arr[::2])    # Every 2nd element → [10 30 50]


10
50
[20 30 40]
[10 30 50]


In [6]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d[0,1])   # Row 0, column 1 → 2
print(arr2d[:,2])   # All rows, column 2 → [3 6]


2
[3 6]


In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)    # [5 7 9]
print(a - b)    # [-3 -3 -3]
print(a * b)    # [4 10 18]
print(a / b)    # [0.25 0.4 0.5]
print(a ** 2)   # [1 4 9]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [8]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))       # Sum → 15
print(np.mean(arr))      # Mean → 3.0
print(np.max(arr))       # Max → 5
print(np.min(arr))       # Min → 1
print(np.std(arr))       # Standard deviation
print(np.arange(0, 10, 2)) # [0 2 4 6 8]
print(np.linspace(0, 1, 5)) # [0.   0.25 0.5  0.75 1. ]


15
3.0
5
1
1.4142135623730951
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [9]:
arr = np.arange(12)  # [0 1 2 ... 11]
arr2d = arr.reshape(3, 4)  # 3 rows, 4 columns
print(arr2d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
arr = np.array([10, 15, 20, 25, 30])
print(arr[arr > 20])  # [25 30]
print(arr)


[25 30]
[10 15 20 25 30]
